language: node_js
sudo: false
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- export PATH=$PWD/node_modules/.bin:$PATH
- polylint
env:
  global:
  - secure: lpU9daiAwETBCDxQjY0yTZpgUnIOIbJnAvVIG2x+TbpBzgfylf1nBPhxmS2eAvInMw2+P65YLMuGqzmrXzr9aK8xsAhvBC5XtbL2r1GIhNLz7QXp/iy4jd3gb1LUTL4rTxLdtuUSg9C4MY9OagIAv8/vCPam1owXRq/MUPdkrOszyo4HL7z2TV7AY5zOSwDP22wmjQc595Wr8fFG0bZTzv4MLeADvZNirbCLCVogrrmgUkLPL3GdcRLLHSpSM4r1oZzd/M4lsrrJVY5UnhOVCEYhXYPCkuVivp0wJ4ror/zKd4OWCr6ALir7i8R/jKcriThUrNmRAmcSe3U+1dBJ12KRmL8B1eKa3Pi97Hpcceaaq+ubiOdet+DlNowO3V7Ub8Zenw+n0iXv1RI3pK4e98dOwW+LAblp7MByJLvu06lJBYMht4uk2bKTEFW920arzyrJieV7fDMjTxkG6a/U3EiApVRomkrmeGu3Gfd1mWcLmiXdE04odAYKItKyO9WvlX3t7IK2HjU3a6A7lUKxhXc/Ryx5hhFkPHy9AFsL7EE4BqGluyCoX38PGnMIeNF3hSOeBdLgdckO3hddBIdVncs0ScMSy4NDgqwouXOjjdp+gHdDl91sXLYotBavq/ItVNNa8IqUTNjIUY6tqRFmj80UUPjQlyHlIZM+aAbsNCE=
  - secure: s7WrVthCpcJafc5j32X5EVzwD6flRN9PB/yGVzS05/0ik7/StKz5Gxryf4QbK08iB3CqxlxgvVrbMQPBnQt7qDLvKFrUhcI+lL4iv0gWI+O2LJA4S6tU6DAh4fOrXpwFYtQPIYueNiq89HPWpWPuBR/hIBIi4EUnAF77NhOPjhyyouVHx7hSBkTdgNbN/eoUsQUfYdSyk4LB/5Ie0GXF0JaGOyQm8BfrdEygfB02fDXQZjdMiVVuwWD1wYezGM3ZmOPLmVy1qXAZp0r84Af5TjIc72bAyjqx8zvlRRvKR4t7mkM7VE/KPbW0xO8irn+nJVghJ36wSxQU5ff5FJxcaHcqnwbGX/IIFIKmHku9Qvewc04a/C/tURshgxXEbKERqTxCqv7eEzILE5rJAPaPf3t07P6N1aPmvN8Bk5rByqRcttIX1eAgkyMuYDpCWguNmuaHtC/EqKpH4I7GPEdzXgztGsfvFxDDn1Vh5sOQdYoysZSXduZAXeZyZB+zpequV5MKIoAeIlaLjjskfdpulBawLUJBx6VREudhzOyUuT2C4AbjsuFg/dc2xuZsH7oaJvdwX1kUVUWFKJg5lI0OgDJVFn4v/XfEVh2QVlNa8kR32WQycSs+psKiloi1Lqz+DRV+u1BDsyEW5XiV/NE0LXYx13pEwCRQ3+E/qolyxfo=
  - CXX=g++-4.8
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    - ubuntu-toolchain-r-test
    packages:
    - google-chrome-stable
    - g++-4.8
  sauce_connect: true
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
